### ISSUE TITLE
Issues with optimizedResize.init()

### ISSUE THREAD

**Issue by nategeier** [kodyl/react-flexr#10]
Does this not work using React 15? I'm trying to run the optimizedResize.init() function the way the app suggests and I'm getting: "index.js:114 Uncaught TypeError: callbacks.setItem is not a function"

When I resize the window I get: "index.js:106 Uncaught TypeError: callbacks.values(...).forEach is not a function"

Everything else works great

**Comment by danieljuhl** [comment]
It works with react 15. Do you have Map available either natively or by polyfill?

**Comment by tanneess** [comment]
I do and the issue is that there is no setItem() method defined for a Map, there is a set() method instead. You can validate this in the MDN doc and here is a print screen of what my Chrome is telling me 
<img width="377" alt="screen shot 2016-07-25 at 23 05 00" src="https://cloud.githubusercontent.com/assets/1636467/17117526/b0e8ed2c-52bc-11e6-8196-6e53a8716a03.png">

**Comment by danieljuhl** [comment]
Ah, then it's probably a general error, and not React 15 related - I'll have a look

**Comment by danieljuhl** [comment]
A new version of `react-flexr` is coming tomorrow, fixing this issue.

**Comment by danieljuhl** [comment]
`react-flexr@2.1.0`
