### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by olivierGM** [kodyl/react-flexr#2]
Hi, i have been playing around for a while and i am having a hard time coming up with a footer concept with this grid system. It seems aligning cells or grid to the bottom doesn't have any effect.

**Comment by chriskjaer** [comment]
Hey @olivierGM,

It should be pretty easy to implement something like a sticky footer.
I just tested the following, and it works without any problems.

```javascript
<Grid style={{ margin: 0, minHeight: '100vh'}}>
  <Cell>...your body goes here...</Cell>
  <Cell size='1/1' align='bottom'>...sticky footer...</Cell>
</Grid>
```

The trick is to make sure the containing Grid component is filling the viewports height, so that when you tell the Cell to align to the bottom of it's container, it's actually at the bottom of the page.

**Comment by olivierGM** [comment]
Ok nice it is working now, thanks. I was thinking like bootstrap. I was thinking that a Grid is row and a Cell is column. This is a good example maybe it would be interesting to have it in the readme ?
